### ISSUE TITLE
Usability: Check dependency on .gitignore rules

### ISSUE THREAD

**Issue by wollmers** [miyagawa/Dist-Milla#20]
It would be better to have error messages directly related to the reason (e.g. "missing gitignore-rule: /Dist-Name-*") than throwing "git-dirty"-messages. In my case last week I wasted 2 hours (installing a new Perl under perlbrew, installing Dist::Milla+Zilla and all dpendencies freshly, because I didn't trust ...) to see the same behaviour ...

**Comment by miyagawa** [comment]
I believe that the error message comes from Git::Check dist zilla plugin.
