### ISSUE TITLE
[@Milla] does not produce a README

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/Dist-Milla#28]
I noticed that `[@Milla]` does not generate a README file. A simple one from `[Readme]` (in `[@Basic]` and core dzil) would be sufficient.  example dist:

https://metacpan.org/source/SCALDWELL/MooseX-Storage-IO-CHI-0.05
http://cpants.cpanauthors.org/dist/MooseX-Storage-IO-CHI

**Comment by miyagawa** [comment]
It does generate a README
https://metacpan.org/release/Dist-Milla

**Comment by miyagawa** [comment]
I just rebuild Milla locally and it doesn't seem to generate a file, and I suspect that something broke Dist-Zilla's ReadmeFromPod plugin.

**Comment by miyagawa** [comment]
Confirmed that Dist::Zilla::Plugin::ReadmeFromPod 0.21 builds README file, but 0.30 (the current latest on PAUSE) does not.
