### ISSUE TITLE
Usability: Check dependency on .dzil/config

### ISSUE THREAD

**Issue by wollmers** [miyagawa/Dist-Milla#33]
If milla setup never was run, or .dzil does not exist, an initial milla build throws misleading and completely useless messages:

helmut@helmut:~/github/Mojolicious-Plugin-ServerInfo$ milla build
[@Milla/NameFromDirectory] guessing your distribution name is Mojolicious-Plugin-ServerInfo
[DZ] Unable to find main_module in the distribution
[DZ] We tried to guess 'lib/Mojolicious/Plugin/ServerInfo.pm' but no file like that existed
[DZ] Upon further inspection we didn't find any files in your dist, did you add any?
[DZ] Cannot continue without a main_module
[DZ] No %User stash and no copyright holder; can't determine dist author; configure author or a %User section
[DZ] No %User stash and no copyright holder; can't determine dist author; configure author or a %User section at /Users/helmut/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/darwin-2level/Moose/Meta/Method/Delegation.pm line 112.

**Comment by karenetheridge** [comment]
This should go to https://github.com/rjbs/dist-zilla/issues -- Dist-Milla is a curated collection of plugins for Dist::Zilla.

**Comment by wollmers** [comment]
@karenetheridge Do have a hint which part/plugin of D::Zilla needs the improvement? Then I can have a look.

**Comment by wollmers** [comment]
Issue of Dist::Zilla.

**Comment by karenetheridge** [comment]
@wollmers it would be in the bits of dzil that I don't well-understand -- somewhere around the call to `->from_config`, but I wonder if the lack of config file should be detected even sooner, e.g. in Config::INI. I'd poke rjbs about it, as it's all his code :)

**Comment by miyagawa** [comment]
Well this might actually have something to do with Milla, or at least one of the plugins loaded by Milla. I'm sure this ticket might be related. https://github.com/rjbs/Dist-Zilla/issues/162

**Comment by wollmers** [comment]
@karenetheridge roughly it looks like $self->files is not filled, if reading of config.* fails. But the fifty shades of indirection, and the fifty levels of dependencies make it fifty magnitudes hard to understand, maintain and test D::Z.

**Comment by wollmers** [comment]
@miyagawa IMHO rjbs/Dist-Zilla#162 has the same reason. If $self->files is not filled, D::Z->main_module guesses correctly (see the messages), but the code from line 200 to 222 is obviously broken.
