### ISSUE TITLE
Available licenses for minting process?

### ISSUE THREAD

**Issue by polettix** [miyagawa/Dist-Milla#36]
During the configuration phase (milla setup) I set the license to Artistic_2_0, which is considered valid (at least, milla didn't complain).

When I run the minting process via `milla new whatever`, anyway, the license in the new module and in LICENSE file is set to "same as Perl 5 itself". I eventually discovered that it's trivial to change to Artistic 2.0 *later* - just edit the module file and do `milla build`. I wonder why specifying a license in the first place anyway.

I'm not totally sure this belongs to Dist::Milla anyway, it might actually be a problem in Dist::Zilla. Any hint would be much appreciated!

**Comment by miyagawa** [comment]
You can change the default module template in `~/.dzil/profiles/default/Module.pm` to override this, I think. Milla will extract the license out of `=head1 LICENSE` there.

**Comment by polettix** [comment]
Not sure this is working for me, it does not seem like Milla is considering that file, nor the entire default profile I was setting up. I'll try to dig this more later.
