### ISSUE TITLE
Support for XS/C/C++ (fork or integrate?)

### ISSUE THREAD

**Issue by wollmers** [miyagawa/Dist-Milla#37]
Missing the convenience of Milla is a pain for releasing XS distributions.

Should I fork to a variant with the name Dist::Milla::C?

Or first develop and later see, if it's easy to integrate?

**Comment by miyagawa** [comment]
Try Minilla since they have XS integration in mind. I have no intent to support XS/C modules because it's pretty much out of scope.

**Comment by karenetheridge** [comment]
Here's what I do for XS-based distributions (via Dist::Zilla::PluginBundle::Author::ETHER):

- include a simplified in-repo Makefile.PL (no prereqs specified; uses ExtUtils::MakeMaker::Dist::Zilla::Develop to ensure the `install` make target is disabled)
- use `[PPPort]` to ensure `ppport.h` is always up to date; copy this file back to the repository and commit it to keep it current for development as well

**Comment by miyagawa** [comment]
Also, are you aware that you can include `[@Milla]` and then add other dzil plugins as you would, so if you want to make another layer of C/XS related bundles they don't need to be in Milla itself, nor a fork.

**Comment by wollmers** [comment]
@karenetheridge Thank's for the hints. Will look into it, maybe need additions or modifications for ExtUtils::CppGuess (see e.g. https://github.com/wollmers/Acme-TestDist-Cpp-EUMM-EUCppGuess/blob/master/Makefile.PL)

**Comment by wollmers** [comment]
@miyagawa Yes, adding plugins is the first approach. But I am not sure, if this will work without changes. 

Thx for the discussion, helped me to get the direction.

Issue solved and I close it.

**Comment by skaji** [comment]
@wollmers FYI https://github.com/skaji/Acme-Dist-Milla-XS

**Comment by wollmers** [comment]
@skaji fine!
