### ISSUE TITLE
Add $VERSION to Dist::Zilla::PluginBundle::Milla

### ISSUE THREAD

**Issue by dolmen** [miyagawa/Dist-Milla#38]
dzil allows to require a minimum version of a bundle with the `:version` option:
```
[@Milla]
:version = v1.0.15
```
Unfortunately, that doesn't work with Dist::Milla because `Dist::Zilla::PluginBundle::Milla` lacks `$VERSION`.

Note: there is also an issue in dzil that does not report this issue gracefully. See rjbs/Dist-Zilla#519.

**Comment by miyagawa** [comment]
Sounds sensible.

**Comment by dolmen** [comment]
Fixed in v1.016.
