### ISSUE TITLE
Add MetaProvides or similar?

### ISSUE THREAD

**Issue by polettix** [miyagawa/Dist-Milla#41]
After [this discussion](https://github.com/perl-carton/carton/issues/210) I got curious and checked my Milla-based modules. None of them has `provides`!

Considering how useful it can be to have `provides` around, does it make sense to add [MetaProvides](https://metacpan.org/pod/Dist::Zilla::Plugin::MetaProvides) to the lot?

**Comment by miyagawa** [comment]
`provides` is only useful when your installed modules are not static, or when you use some weird syntax such as MooseX::Declare. Milla assumes you're using static list of .pm files in a plain perl syntax under `lib`, so MetaProvides should not be necessary.

But if you want to add it you can always just add `[MetaProvides]` in the ini file.
