### ISSUE TITLE
recommend plugin switch: VersionFromModule -> RewriteVersion

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/Dist-Milla#42]
The `[VersionFromModule]` plugin no longer passes tests, and is no longer being actively maintained -- but `[RewriteVersion]` can be used as a drop-in replacement.

**Comment by miyagawa** [comment]
the plugin is not updated because it is considered feature complete. If the tests are failing I'd love to fix that instead.

**Comment by karenetheridge** [comment]
This isn't `[LicenseFromModule]` (which is yours), but `[VersionFromModule]`, by someone who seems to have dropped off the edge of the perl planet in the last year or two. Given that issues have existed for some time with no appearance by the author, it's reasonable to try to mitigate the lack of clean builds by migrating to another plugin that provides the desired features but is being maintained.

**Comment by miyagawa** [comment]
lol, i was thinking VersionFromModule was mine!

**Comment by Grinnz** [comment]
There is still no update to [VersionFromModule]. It has also been forked to https://metacpan.org/pod/Dist::Zilla::Plugin::VersionFromMainModule in the meantime.

**Comment by karenetheridge** [comment]
`[VersionFromMainModule]` would be a very reasonable switch -- it is a good drop-in replacement for `[VersionFromModule]`.

**Comment by miyagawa** [comment]
That looks reasonable!

**Comment by karenetheridge** [comment]
Is a release possible?  Presently Milla does not install cleanly, which is causing some confusion among neophyte users.

**Comment by miyagawa** [comment]
i'm away from the dev computer at this moment - can one of you make a PR for the switch?

**Comment by miyagawa** [comment]
This has been fixed and released to CPAN.
