### ISSUE TITLE
Run test.pl on build/test?

### ISSUE THREAD

**Issue by jbakerdev** [miyagawa/Dist-Milla#51]
Pardon my ignorance if there's a better way to do this (or if I'm doing something dumb)... I'd like Milla to use yath instead of prove. Per the [Test2 docs](https://github.com/Test-More/Test2-Harness/#making-your-project-always-use-yath):

> MAKING YOUR PROJECT ALWAYS USE YATH
>
> `$ yath init`
>
> The above command will create test.pl. test.pl is automatically run by most build utils, in which case only the exit value matters. The generated test.pl will run yath and execute all tests in the ./t and/or ./t2 directories. Tests in ./t will ALSO be run by prove but tests in ./t2 will only be run by yath.

But my milla projects don't seem to even run test.pl? Is that by design or am I doing something wrong?

**Comment by Grinnz** [comment]
test.pl is used by CPAN *install* tools - Module::Build::Tiny, which Milla uses by default, does not support test.pl for running tests. You can switch to another installer like EUMM for your distribution simply:

```
[@Milla]
installer = MakeMaker
```

**Comment by jbakerdev** [comment]
Ah, there it is... like I said, pardon my ignorance!
