### ISSUE TITLE
Support extracting minimum perl version 

### ISSUE THREAD

**Issue by miyagawa** [miyagawa/Dist-Milla#7]
Module::Install had `perl_version_from` which extracts *only* perl minimum version dependency from .pm file.

dzil's [AutoPrereqs] or [Perl::MinimumVersion] plugin can replace this.

**Comment by karenetheridge** [comment]
`[MinimumPerl]` is what you want here.

**Comment by miyagawa** [comment]
Not quite. M::I's `perl_version_from` just detects `use 5.010` kind of declaration and adds that to the metadata. 

I know what Perl::MinimumVersion does and while it is a great code, I think it's too magical and smart to do when it's done automatically by the framework. Of course you can add it on your own, but don't think it should be included by default.

Right now we dump the perl requirement in `milla new` profile in `cpanfile`, and I think it's a useful to way to declare perl requirement in the file, rather than figuring out from the code, since it can be detected by other tools as well.
